#!/usr/bin/env bash
set -eu -o pipefail

PASSED=false
trap 'ec=$?; $PASSED || { echo 1>&2 "*** FAILED (exitcode=$ec)"; }' 0

basedir=$(cd "$(dirname "$0")" && pwd -P)
cd "$basedir"

[[ ${#@} -gt 0 && $1 == -C ]] && { shift; rm -rf .build/; }
. ./pactivate -q
export PYTHONPATH="$basedir/pylib"

####################################################################
#   Unit Tests

[[ ${#@} -eq 0 ]] && set pylib/
pytest -q "$@"

####################################################################
#   Functional Tests

ftdata=.build/programs/
mkdir -p $ftdata

bin/detok    programs/simple.bas >$ftdata/simple.ba0
diff -u {$ftdata,programs}/simple.ba0

bin/detok -e programs/simple.bas >$ftdata/simple.ba1
diff -u {$ftdata,programs}/simple.ba1

PASSED=true
