#!/usr/bin/env bash
set -eu -o pipefail

PASSED=false
trap 'ec=$?; $PASSED || { echo 1>&2 "*** FAILED (exitcode=$ec)"; }' 0

basedir=$(cd "$(dirname "$0")" && pwd -P)
cd "$basedir"

[[ ${#@} -gt 0 && $1 == -C ]] && { shift; rm -rf .build/; }
. ./pactivate -q
export PYTHONPATH="$basedir/pylib"

####################################################################
#   Unit Tests

[[ ${#@} -eq 0 ]] && set pylib/
pytest -q "$@"

####################################################################
#   Functional Tests

diff -u programs/simple.ba <(bin/detok -e programs/simple.bas)

PASSED=true
